vim.keymap.set("n", "<leader>pv", vim.cmd.Ex)
vim.keymap.set("n", ",q", "<Cmd>q<Cr>")
vim.keymap.set("n", ",w", "<Cmd>w<Cr>", { desc = "Write current buffer" })

-- Center buffer while navigating
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "{", "{zz")
vim.keymap.set("n", "}", "}zz")
vim.keymap.set("n", "N", "Nzz")
vim.keymap.set("n", "n", "nzz")
vim.keymap.set("n", "G", "Gzz")
vim.keymap.set("n", "gg", "ggzz")
vim.keymap.set("n", "<C-i>", "<C-i>zz")
vim.keymap.set("n", "<C-o>", "<C-o>zz")
vim.keymap.set("n", "%", "%zz")
vim.keymap.set("n", "*", "*zz")
vim.keymap.set("n", "#", "#zz")
-- Press 'H', 'L' to jump to start/end of a line (first/last char)
-- vim.keymap.set("n", "L", "$")
-- Add any additional keymaps here
